#!/bin/bash

#Verifica o gerenciador de pacotes e define variaveis para usa-lo

dnf -h &> /dev/null
if [ $? -eq 0 ]; then
    export PKG=dnf
    export PKG_INSTALL="dnf install"
    export PKG_UPDATE="dnf update"
fi

yum -h &> /dev/null
if [ $? -eq 0 ]; then
    export PKG=yum
fi

pacman -h &> /dev/null
if [ $? -eq 0 ]; then
    export PKG=pacman
    export PKG_INSTALL="pacman -Sy"
    export PKG_UPDATE="pacman -Syyu"
fi

apt-get -h &> /dev/null
if [ $? -eq 0 ]; then
    export PKG=apt-get
    export PKG_INSTALL="apt-get install -y"
    export PKG_UPDATE="apt-get update && apt-get dist-upgrade -y && apt-get autoremove --purge -y && apt-get clean"
fi
